services:
  achat.api:
    image: achat.api
    build:
      context: .
      dockerfile: AChat.API/Dockerfile
    ports:
      - "18080:8080"
      - "18081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_URLS=https://+:8081
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Admin123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    env_file:
      - stack.env
    pull_policy: build
    restart: unless-stopped
